project_name: s3proxy

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: s3proxy
    main: ./cmd/s3proxy
    binary: s3proxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: s3proxy
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*
      - .env.example

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

nfpms:
  - id: s3proxy
    package_name: s3proxy
    vendor: S3Proxy
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    maintainer: S3Proxy Team
    description: High-performance S3-compatible proxy with encryption support
    license: Apache 2.0
    formats:
      - deb
      - rpm
    dependencies:
      - systemd
    contents:
      - src: s3proxy
        dst: /usr/bin/s3proxy
      - src: config-test.yaml
        dst: /etc/s3proxy/config.yaml.example
        type: config
      - src: ./systemd/s3proxy.service
        dst: /lib/systemd/system/s3proxy.service
    scripts:
      postinstall: ./scripts/postinstall.sh
      preremove: ./scripts/preremove.sh

nsis:
  - id: s3proxy-installer
    name: S3Proxy-{{ .Version }}-Windows-{{ .Arch }}-installer
    homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
    license: LICENSE
    script: installer.nsi
    include:
      - LICENSE
      - README.md
      - config-test.yaml

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'Features'
      regexp: '^feat'
    - title: 'Bug Fixes'
      regexp: '^fix'
    - title: 'Performance'
      regexp: '^perf'
    - title: 'Security'
      regexp: '^security'
    - title: 'Other'

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .ProjectName }}"
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## S3Proxy {{.Version}}

    High-performance S3-compatible proxy with support for multiple storage backends.

  footer: |
    ## Installation

    ### Windows
    Download and run the Windows installer: `S3Proxy-{{ .Version }}-Windows-x86_64-installer.exe`

    ### Linux (Debian/Ubuntu)
    ```bash
    dpkg -i s3proxy_{{ .Version }}_amd64.deb
    systemctl start s3proxy
    ```

    ### Linux (RHEL/CentOS)
    ```bash
    rpm -i s3proxy_{{ .Version }}_amd64.rpm
    systemctl start s3proxy
    ```

    ## Docker Images

    ```bash
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Version }}
    docker pull ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest
    ```

    ## Helm Chart

    ```bash
    helm repo add s3proxy https://{{ .Env.GITHUB_REPOSITORY_OWNER }}.github.io/{{ .ProjectName }}
    helm install s3proxy s3proxy/s3proxy --version {{ .Version }}
    ```

# Homebrew tap (optional - requires separate tap repository)
# brews:
#   - name: s3proxy
#     homepage: https://github.com/{{ .Env.GITHUB_REPOSITORY }}
#     description: "High-performance S3-compatible proxy"
#     license: "Apache-2.0"
#     tap:
#       owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
#       name: homebrew-tap
#     folder: Formula
