extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  indentation:
    spaces: 2
    indent-sequences: true
  document-start:
    present: false
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']

ignore: |
  examples/kubernetes/
  charts/s3proxy/examples/values-velora.yaml
